### ISSUE TITLE
Implement MVP

### ISSUE THREAD

**Issue by Glavin001** [Unibeautify/unibeautify-cli#1]
- [x] Use [`Unibeautify`](https://github.com/Glavin001/unibeautify)
- ~~Use [`listr`](https://github.com/samverschueren/listr)~~
  - See https://github.com/sindresorhus/np for example.
- ~~Use [`insight`](https://github.com/yeoman/insight)~~
- ~~Detect beautifiers named `beautifier-${name}`~~ Moved to #4.
  - See https://github.com/yeoman/environment/blob/f9468481911c31673378b38e63872f57a1163f38/lib/resolver.js#L63 for example.

**Comment by prettydiff** [comment]
I have a 60% solution.  https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js

I have separated out the Pretty Diff options madness.  Pretty Diff now centrally manages its options in an external library.  The goal of this file is go as quickly as possible when reading multiple files.  This node-local library performs these tasks:

* Reads a variety of input formats using the option `readmethod`.
   - `screen` - reads input from a cli argument directly and outputs to the terminal
   - `filescreen` - reads input from a file and outputs to the terminal
   - `file` - reads from a file and writes output to a file (requires an option named *output*)
   - `directory` - reads from a single directory and writes a directory of output (requires an option named *output*)
   - `subdirectory` - recursively reads from an entire directory tree writes out that directory tree elsewhere with beautified files (requires and option named *output*)
   - `auto` - The default value performs a stat on the input value to determine if its a file, directory, or neither and then sets readmethod value to screen, file, or subdirectory.
* When processing multiple files simultaneously there can be race conditions and collisions in the updating of additional data artifacts outside the immediate file contents.  The node-local file uses an option *nodeasync* to identify to other libraries the need to isolation additional data in order to prevent collisions.
* It has a mechanism to determine if a file's contents are binary or text.  Text file data is easy to manage in Node using fs.readFile and fs.writeFile.  Binary files require the opening of a streaming and collecting data as a buffer.  The file manages this appropriately.  The need arises when using readmethod directory or subdirectory and some files need to be read and written to the new location (even if not processed by a beautifier) to ensure the output directory has all the original files.

Additional tasks:

* Right now the file is still Pretty Diff centric with the libraries it lists at the top.  This will clearly need to be replaced with library management for the various beautifiers.
* There still might be some Pretty Diff centered options used for decisions in the file (possibly for language identification).  I need to go back and identify these.
* There is additional overhead in the file for diff mode that would need to be removed for this project.  Reading two separate directory trees and determining which file from the source input should be compared against which file from the diff input requires additional logic when processing multiple files simultaneously as fast as possible.
